version: '3.7'

services:    
  php-apache:
    container_name: test-php
    build: ./docker/php
    volumes:
    - ./server:/var/www/html
    - ./docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
    - 80:80
    depends_on:
    - db

  db:
    image: mariadb
    container_name: test-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/mariadb.cnf:/etc/mysql/mariadb.cnf
    ports:
    - 3306:3306
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    depends_on:
      - db